experimentName: MySRec-amazon_beauty
searchSpaceFile: ../search_space/SparseEnNet.json

trialCommand: python3 main.py --data_name Toys_and_Games  --batch_size 256 --num_cluster 256 --seq_representation_type mean --num_hidden_layers 3 --tune True --output_dir nni_result/
trialCodeDirectory: ..
trialGpuNumber: 1

trialConcurrency: 3            # Run 4 trials concurrently.
maxTrialNumber: 1000              # Generate at most 10 trials.
maxExperimentDuration: 100d       # Stop generating trials after 1 hour.

tuner:                          # Configure the tuning algorithm.
  name: TPE
  classArgs:
    optimize_mode: maximize

# assessor:
#   name: Curvefitting
#   classArgs:
#     epoch_num: 200
#     start_step: 20
#     threshold: 0.9
#     gap: 1

# assessor:
#   name: Medianstop
#   classArgs:
#     optimize_mode: maximize
#     start_step: 200
# Configure the training platform.
# Supported platforms: local, remote, openpai, aml, kubeflow, kubernetes, adl.

trainingService:
  platform: local
  useActiveGpu: true
  gpuIndices: 0,1,2,3
  maxTrialNumberPerGpu: 1
